format = '$username$hostname$directory${custom.giturl}$all'
command_timeout = 750

[hostname]
ssh_symbol = '@'
format = '[$ssh_symbol $hostname]($style) '

[username]
format = '[$user]($style) '

[gcloud]
disabled = true
format = '[ïƒ‚ $project]($style) '

[gcloud.project_aliases]
very-long-project-name = 'vlpn'

[package]
display_private = true
format = "[ðŸ“¦ $version](208 bold) "

[nodejs]
detect_extensions = []
detect_folders = []
detect_files = [".nvmrc", ".node_version"]
format = "[îœ˜ $version ](bold green) "

[rust]
format = "[$symbol($version )]($style)"

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[git_branch]
format = "[$symbol$branch(:$remote_name/$remote_branch)]($style) "

[git_metrics]
disabled = false

[helm]
format = '[âŽˆ $version](bold white) '

[kubernetes]
disabled = false
detect_files = ['k8s']

[docker_context]
disabled = true
format = '[ïŒˆ $context](blue bold) '

[cmd_duration]
format = '[ï€— $duration](bold yellow) '

[lua]
format = '[$symbol($version )](bold yellow) '

[bun]
format = '[$symbol($version )]($style) '
style = 'fg:179'

[php]
format = '[$symbol($version )]($style) '

[dart]
format = '[$symbol($version )]($style) '

[gradle]
format = '[$symbol($version )]($style) '

[java]
format = '[$symbol($version )]($style) '

[terraform]
format = '[$symbol$workspace]($style)'

[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL="ïˆ "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL="ïŠ– "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL="ï…± "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL="ïž¡ "
else
    GIT_REMOTE_SYMBOL="ï‡’ "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "$output  "
